variables:
  MY_PROJECT_ID: "12928828"
  GIT_SYNC_URL: "https://$GITHUB_USERNAME_ROBOT:$GITHUB_TOKEN_ROBOT@github.com/NoFussComputing/docker-glpi.git"
  

  DOCKER_IMAGE_BUILD_TARGET_PLATFORMS: "linux/amd64,linux/arm64,linux/arm/v7"
  DOCKER_IMAGE_PUBLISH_NAME: 'docker-glpi'
  DOCKER_IMAGE_PUBLISH_REGISTRY: docker.io/nofusscomputing
  DOCKER_IMAGE_PUBLISH_URL: https://hub.docker.com/r/nofusscomputing/$DOCKER_IMAGE_PUBLISH_NAME
  PAGES_ENVIRONMENT_PATH: projects/glpi/
  PIP_BREAK_SYSTEM_PACKAGES: '1'

include:
  - project: nofusscomputing/projects/gitlab-ci
    ref: development
    file:
      - template/automagic.gitlab-ci.yaml
  #- template: Jobs/Container-Scanning.gitlab-ci.yml # see https://gitlab.com/gitlab-org/gitlab/-/issues/381665


Website.Submodule.Deploy:
  extends: .submodule_update_trigger
  variables:
    SUBMODULE_UPDATE_TRIGGER_PROJECT: nofusscomputing/infrastructure/website
  environment:
    url: https://nofusscomputing.com/$PAGES_ENVIRONMENT_PATH
    name: Documentation
  rules:
    - if:  # condition_dev_branch_push
        $CI_COMMIT_BRANCH == "development" && 
        $CI_PIPELINE_SOURCE == "push"
      exists:
        - '{docs/**,pages/**}/*.md'
      changes:
        paths:
          - '{docs/**,pages/**}/*.md'
        compare_to: 'master'
      when: always

    - when: never
